name: Build ProtonVPN APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Android Command Line Tools
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk
          cd /usr/local/lib/android/sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -qq commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mkdir cmdline-tools && mv cmdline-tools cmdline-tools/latest

      - name: Set ANDROID_HOME and update SDK
        run: |
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV
          yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      - name: Install SWIG
        run: sudo apt-get update && sudo apt-get install -y swig

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug
